### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by Z-Y00** [alibaba/acqdp#16]
Hi, I just cloned and run the acqdp with the command shown below, and I found a error.
I redirected the output to a log, and I pasted both stderr and stdout as below: 
```
(qulacs) [gengyura@d05-37 acqdp]$ python3 ./examples/circuit_simulation.py benchmark/circuit_n53_m10_s0_e0_pABCDCDAB.qsim --save-order opt-m10 > m10-origional-d05-37.log

Traceback (most recent call last):
  File "./examples/circuit_simulation.py", line 149, in <module>
    tsk = tn.compile(order, **kwargs)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/tensor_network.py", line 113, in compile
    return Compiler(**kwargs.get('compiler_params', {})).compile(self, order)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/compiler.py", line 50, in compile
    res = self._generate_template(tn, scheme=scheme, **kwargs)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/compiler.py", line 70, in _generate_template
    init_order, final_order = self._order_patch(tn_copy.copy(), order, split,
  File "/home1/gengyura/acqdp/acqdp/tensor_network/compiler.py", line 220, in _order_patch
    final_order = self._patch_order(tn_copy, final_order)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/compiler.py", line 258, in _patch_order
    res = tree.patch(self.patch_size)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/contraction_tree.py", line 278, in patch
    self.merge_nodes(width)
  File "/home1/gengyura/acqdp/acqdp/tensor_network/contraction_tree.py", line 183, in merge_nodes
    m0 = m0.union(brb[0][i][1]).difference(brb[0][i][2])
IndexError: list index out of range
```
in the log:
```
(3_w,7)-aCMA-ES (mu_w=2.3,w_1=58%) in dimension 3 (seed=698316605, Tue Jan 19 05:15:47 2021)
Iterat #Fevals   function value  axis ratio  sigma  min&max std  t[m:s]
    1      7 1.119770173288873e+01 1.0e+00 1.93e-01  2e-01  2e-01 0:08.2
    2     14 1.125634101323780e+01 1.4e+00 1.68e-01  1e-01  2e-01 0:14.4
    3     21 1.127719546809599e+01 1.6e+00 1.53e-01  1e-01  2e-01 0:21.5
    4     28 1.136495725718497e+01 1.7e+00 1.32e-01  9e-02  1e-01 0:28.4
    5     35 1.119770173288873e+01 1.7e+00 1.17e-01  7e-02  1e-01 0:35.5
    6     42 1.125634101385395e+01 1.7e+00 1.32e-01  8e-02  1e-01 0:42.5
    7     49 1.134322401217997e+01 1.7e+00 1.47e-01  8e-02  1e-01 0:48.7
    9     63 1.119393613620733e+01 2.2e+00 1.06e-01  4e-02  1e-01 1:02.1
Process 0 initial cost: cost = 10.94684080523537, cw = 28.0, num_slice = 0
Process 0 succeeded with cost = 10.708556981162134, cw = 26.0, num_slice = 0
cost = 10.708556981162134, cw = 26.0, num_slice = 0
Saving order file opt-m10


```

**Comment by Z-Y00** [comment]
This bug happens randomly, I'm unable to reproduce it with the same configuration

**Comment by dmikushin** [comment]
Maybe try to disable multithreading?
